spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ptl_dev
    username: ptl_dev_user
    password: navneet
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true